mejoras en el QR

diff --git a/bin/secreto b/bin/secreto
--- a/bin/secreto
+++ b/bin/secreto
@@ -32,8 +32,14 @@ function opciones {
 	# genera el menu
 	eval "zenity --title \"$TITULO\" --text \"$MENSAJE\" --list --height=250 --column \"\" --column \"\" --hide-column 1  --hide-header $C"
 }
+function cifrar {
+	cat /dev/stdin | mcrypt -u -k "$1" -F | base64 $2
+}
+function descifrar {
+	 cat /dev/stdin | base64 -d | mdecrypt - -k "$1" -F
+}
 function error {
-	zenity --error
+	zenity --error --text="$*"
 }
 function alerta {
 	zenity --warning --text="$(cat /dev/stdin)"
@@ -116,7 +122,7 @@ case $MENU in
 	0 )
 	# Cifrar
 	#------------------ entrada ----------------------
-	MENU=`echo -e "Mensaje Archivo" | opciones -t "Ciframe" -m "¿Que deseas proteger?"` || exit
+	MENU=`echo -e "Escribir_mensaje Archivo" | opciones -t "Ciframe" -m "¿Que deseas proteger?"` || exit
 	case $MENU in
 		0 )
 			ef=`mensaje`
@@ -130,7 +136,7 @@ case $MENU in
 	case $MENU in
 		0 )
 		# genera el mensaje y lo muestra en base64
-		m=`echo "$ef" | mcrypt -u -k "$k" -F | base64`
+		m=`echo "$ef" | cifrar "$k"`
 		echo "$m" | portapapeles
 		echo "$m" | mostrar
 		;;
@@ -178,7 +184,7 @@ case $MENU in
 		3 )
 		# publicar en tinyURL con Tor
 		# genera el mensaje y lo muestra en base64
-		m=`echo "$ef" | mcrypt -u -k "$k" -F | base64 -w0`
+		m=`echo "$ef" | cifrar "$k"  -w0`
 		for N in {1,2,3}; do
 			sleep 3 | progreso &
 			# si no se puede genera la tinyurl prueba varias veces
@@ -192,7 +198,7 @@ case $MENU in
 		4 )
 		# genera el mensaje y lo muestra en base64
 		f=`mktemp`
-		echo "$ef" | mcrypt -u -k "$k" -F | base64 > $f
+		echo "$ef" | cifrar "$k"  > $f
 		#proxychains
 		PASTIE=`wgetpaste -S | sed 's/[^a-z|]//g; s/|.*$//g' | sed -n $[$RANDOM%7+2]p`
 		proxychains wgetpaste -g -r -n $(pwgen -1) -s $PASTIE $f | sed -n '2p' | sed 's/^.*://'| mostrar
@@ -213,7 +219,10 @@ case $MENU in
 		5)
                 # genera codigo QR
 		cd $PICTURES
-		qrencode -o $(pwgen -1).png "$(echo "$ef" | mcrypt -u -k "$k" -F | base64 -w0)"
+		sf=`pwgen -1`.png
+		qrencode -o "$sf" "$(echo "$ef" | cifrar "$k" -w0)" || error "Los QR tienen espacio limitado"
+		convert -strip "$sf" "$sf"
+		echo "$(pwd)/$sf" | mostrar "Codigo QR generado"
 	;;
 	esac
 	;;
@@ -221,13 +230,13 @@ case $MENU in
 	# Descifrar
 
 	# mensaje archivo o URL
-	MENU=`echo -e "Mensaje Archivo_o_Codigo_QR En_la_red" | opciones -t "Descifrar" -m "¿Donde queres buscar?"` || exit
+	MENU=`echo -e "Mensaje Archivo_o_Codigo_QR Dirección_web" | opciones -t "Descifrar" -m "¿Donde queres buscar?"` || exit
 	case $MENU in
 		0 )
 			# descifrado
 			t=`mensaje` || exit
 			k=`clave`
-			m=`$t | sed 's/[^0-9A-Za-z=\/+]//g'| base64 -d | mdecrypt - -k "$k" -F` || error && exit
+			m=`$t | sed 's/[^0-9A-Za-z=\/+]//g'| descifrar "$k"` || error && exit
 
 			# lo guarda en la portapapeles y lo muestra
 			echo "$m" | portapapeles
@@ -238,7 +247,7 @@ case $MENU in
 			sf=`archivo` || exit
 			# mensaje descifrado en archivo
 			p=`clave`
-			m=`zbarimg --raw -q "$sf" | base64 -d | mdecrypt - -k "$k" -F || \
+			m=`zbarimg --raw -q "$sf" | descifrar "$p" || \
 			steghide extract -p "$p" -sf "$sf" -xf -`
 			echo "$m" | mostrar
 		;;
@@ -264,20 +273,19 @@ case $MENU in
 				tipo=`file -i $f | sed 's/^.*:\ //g; s/\/.*$//g'`
 				sf=`cat $f`
 				# borra el archivo temporal
-				shred -uz -n 10 $f
 			fi
 			# interpreta depende si es cifrado o estenografia
 			if [ "$tipo" == "text" ]; then
 				# si es un texto
 				m=`echo $sf | tr "\n" " " | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' \
-				| sed 's/[^0-9A-Za-z=\/+-]//g'| base64 -d | mdecrypt - -k "$p" -F`
+				| sed 's/[^0-9A-Za-z=\/+-]//g'| descifrar "$p"`
 			else
-
-				# si es archivo
-				m=`echo "$sf" | steghide extract -p "$p" -sf - -xf -`|| error
+				m=`zbarimg --raw -q "$f" | descifrar "$p" || \
+				steghide extract -p "$p" -sf "$f" -xf -`
 			fi
 			# borrar el archivo temporal para siempre
 			echo "$m" | mostrar
+			shred -uz -n 10 $f
 		;;
 	esac
 
@@ -343,3 +351,4 @@ exit
 ## Quehaceres
 
 - hacer mas generico el instalador
+- simplificar
