un poco mas simple

diff --git a/bin/secreto b/bin/secreto
--- a/bin/secreto
+++ b/bin/secreto
@@ -32,6 +32,16 @@ function opciones {
 	# genera el menu
 	eval "zenity --title \"$TITULO\" --text \"$MENSAJE\" --list --height=250 --column \"\" --column \"\" --hide-column 1  --hide-header $C"
 }
+function metadatos {
+	convert -strip "$1" "$1"
+}
+function pastie {
+	f=`mktemp`
+	cat /dev/stdin > $f
+	PASTIE=`echo "bpaste ca codepad dpaste gists poundpython" | sed 's/\ /\n/g'| sed -n $[$RANDOM%6+1]p`
+	proxychains wgetpaste -g -r -n $(pwgen -s -1) -s $PASTIE $1 | sed -n '2p' | sed 's/^.*:\ //'
+	shred -uz -n 10 $f
+}
 function cifrar {
 	cat /dev/stdin | mcrypt -u -k "$1" -F | base64 $2
 }
@@ -196,16 +206,11 @@ case $MENU in
 		url "$u"
 		;;
 		4 )
-		# genera el mensaje y lo muestra en base64
-		f=`mktemp`
-		echo "$ef" | cifrar "$k"  > $f
-		#proxychains
-		PASTIE=`echo "bpaste ca codepad dpaste gists poundpython" | sed 's/\ /\n/g'| sed -n $[$RANDOM%6+1]p`
-		proxychains wgetpaste -g -r -n $(pwgen -s -1) -s $PASTIE $f | sed -n '2p' | sed 's/^.*://'| mostrar
-		#nopaste-it -f "$f" | sed -n '2p' | sed 's/\t//g'
-		shred -uz -n 10 $f
+			# genera el mensaje y lo muestra en base64
+			echo "$ef" | cifrar "$k" | pastie | mostrar
 
 		exit
+		# nopaste-it -f "$f" | sed -n '2p' | sed 's/\t//g'
 		# "http://www.cjb.net/"=>{"image"=>"____"},
    		# "http://kimag.es/"=>{"userfile1"=>"____"},
 		# "http://tinypic.com/"=>{"the_file"=>$ARGV[0]}
@@ -217,12 +222,12 @@ case $MENU in
 
 	   	;;
 		5)
-                # genera codigo QR
-		cd $PICTURES
-		sf=`pwgen -1`.png
-		qrencode -o "$sf" "$(echo "$ef" | cifrar "$k" -w0)" || error "Los QR tienen espacio limitado"
-		convert -strip "$sf" "$sf"
-		echo "$(pwd)/$sf" | mostrar "Codigo QR generado"
+	                # genera codigo QR
+			cd $PICTURES
+			sf=`pwgen -1`.png
+			qrencode -o "$sf" "$(echo "$ef" | cifrar "$k" -w0)" || error "Los QR tienen espacio limitado"
+			metadatos "$sf"
+			echo "$(pwd)/$sf" | mostrar "Codigo QR generado"
 	;;
 	esac
 	;;
@@ -294,17 +299,14 @@ case $MENU in
 	2 )
 		# publicacion anonima
 		f=`mktemp`
-		mensaje > $f || exit
-		PASTIE=`wgetpaste -S | sed 's/[^a-z|]//g; s/|.*$//g' | sed -n $[$RANDOM%7+2]p`
-		proxychains wgetpaste -g -r -n $(pwgen -1) -s $PASTIE $f | sed -n '2p' | sed 's/^.*://' | mostrar
-		shred -uz -n 10 $f
+		mensaje | pastie | mostrar
 	;;
 	3 )
 		# Quitar metadatos
 		archivos  || exit | while read ARCHIVO; do
 			# falta quitar las caras
 			# opcion para romper pixels
-			convert -strip "$ARCHIVO" "$ARCHIVO"
+			metadatos "$ARCHIVO"
 		done | progreso
 	;;
 	4 )
