mas pequeño

diff --git a/bin/secreto b/bin/secreto
--- a/bin/secreto
+++ b/bin/secreto
@@ -221,7 +221,7 @@ case $MENU in
 	# Descifrar
 
 	# mensaje archivo o URL
-	MENU=`echo -e "Mensaje Archivo En_la_red Codigo_QR" | opciones -t "Descifrar" -m "¿Donde queres buscar?"` || exit
+	MENU=`echo -e "Mensaje Archivo_o_Codigo_QR En_la_red" | opciones -t "Descifrar" -m "¿Donde queres buscar?"` || exit
 	case $MENU in
 		0 )
 			# descifrado
@@ -238,7 +238,9 @@ case $MENU in
 			sf=`archivo` || exit
 			# mensaje descifrado en archivo
 			p=`clave`
-			steghide extract -p "$p" -sf "$sf" -xf - | mostrar
+			m=`zbarimg --raw -q "$sf" | base64 -d | mdecrypt - -k "$k" -F || \
+			steghide extract -p "$p" -sf "$sf" -xf -`
+			echo "$m" | mostrar
 		;;
 		2 )
 			# url
@@ -270,17 +272,11 @@ case $MENU in
 				m=`echo $sf | tr "\n" " " | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' \
 				| sed 's/[^0-9A-Za-z=\/+-]//g'| base64 -d | mdecrypt - -k "$p" -F`
 			else
+
 				# si es archivo
-				m=`echo "$sf" | steghide extract -p "$p" -sf - -xf -`
+				m=`echo "$sf" | steghide extract -p "$p" -sf - -xf -`|| error
 			fi
 			# borrar el archivo temporal para siempre
-			echo "$m" | mostrar
-		;;
-		3)
-			# descifrado de QR
-			f=`archivo` || exit
-			k=`clave`
-			m=`zbarimg --raw $f | base64 -d | mdecrypt - -k "$k" -F` || error
 			echo "$m" | mostrar
 		;;
 	esac
