version funcional al 90%

diff --git a/bin/secreto b/bin/secreto
--- a/bin/secreto
+++ b/bin/secreto
@@ -25,29 +25,33 @@ function opciones {
 		N=$(($N+1))
 	done
 	# genera el menu
-	eval "zenity --title \"$TITULO\" --text \"$MENSAJE\" --list --column \"\" --column \"\" --hide-column 1  --hide-header $C"
-
+	eval "zenity --title \"$TITULO\" --text \"$MENSAJE\" --list --height=250 --column \"\" --column \"\" --hide-column 1  --hide-header $C"
 }
 function error {
 	zenity --error
 }
 function clave {
-	zenity --title "Clave" --text "Introduce la clave" --entry
+	zenity --title "Clave" --text "Introducir la clave" --entry --entry-text="$*"
 }
 function url {
-	zenity --title "URL" --text "Introducir dirección" --entry
+	zenity --title "URL" --text "Dirección" --entry --entry-text="$*"
 }
 function archivo {
-	zenity --title "elije el archivo" --file-selection
+	zenity --title "Elije el archivo" --file-selection
 }
 function archivos {
 	echo -e "$(zenity --title "Archivos" --title "Elije el archivos" --file-selection --multiple --separator="\n")"
 }
 function mensaje {
-	zenity --title "Mensaje" --text="introduce el mensaje" --text-info --editable
+	zenity --title "Mensaje" --text="introduce el mensaje" --width=450 --height=350 --text-info --editable
 }
 function mostrar {
-	cat /dev/stdin | zenity --title "Mensaje" --text="¡Listo!" --text-info
+	MENSAJE=`cat /dev/stdin`
+	if [ "$(echo $MENSAJE | wc -l )" == "1" ]; then
+		zenity --title "Mensaje" --entry --entry-text="$MENSAJE"
+	else
+		echo "$MENSAJE" | zenity --title "Mensaje" --width=450 --height=350 --text="¡Listo!" --text-info
+	fi
 }
 function papelera {
 	cat /dev/stdin | xsel
@@ -75,12 +79,12 @@ case $MENU in
 			ef=`cat $(archivo || exit)`
 		;;
 	esac
-	k=`pwgen  -1 -s |clave`
+	k=`clave $(pwgen  -1 -s)`
 	MENU=`echo -e "Mensaje Archivo Imagen_al_azar tinyURL Publicar" | opciones -t "¿En donde?" -m "¿Donde lo queres ocultar?"` || exit
 	case $MENU in
 	0 )
 		# genera el mensaje y lo muestra en base64
-		m=` echo "$ef" | mcrypt -z -u -k "$k" -F | base64 -w0 `
+		m=`echo "$ef" | mcrypt -u -k "$k" -F | base64`
 		echo "$m" | papelera
 		echo "$m" | mostrar
 		;;
@@ -92,46 +96,50 @@ case $MENU in
 	2 )
 		# busca una imagen al azar en la web (con tor)
 		# http://thepaperwall.com/rss.recentfifty.php
-		# 
+		img_url=`proxychains wget -qO - http://www.nasa.gov/rss/lg_image_of_the_day.rss \
+		| grep -o '<enclosure [^>]*>' \
+		| grep -o 'http://[^\"]*' | head -n 1`
+		# ↑ esto deberia ser al azar y no estar en la NSA
+		# directorio
 		p=`clave`
-		echo "$ef" | steghide embed -ef - -p "$k" -cf "$b"
+		cf="$(pwgen -1 -s).jpg"
+		# proxy
+		cd $PICTURES
+		echo $img_url > /dev/stderr
+		proxychains wget "$img_url" -O "$cf"
+		echo "$ef" | steghide embed -ef - -p "$p" -cf "$cf"
+		xdg-open .
 		;;
 	3 )
 		# publicar en tinyURL con Tor
 		# genera el mensaje y lo muestra en base64
-		m=`echo "$ef" | mcrypt -z -u -k "$k" -F | base64 -w0`
-		u=`wget -U Mozilla "https://tinyurl.com/create.php?url=data:text/html;charset=utf-8;base64,$m" -qO - \
-		| grep "https://tinyurl.com/"` | progreso
-		echo "$u" > /dev/stderr
+		m=`echo "$ef" | mcrypt -u -k "$k" -F | base64 -w0`
+		for N in {1,2,3}; do
+			sleep 3 | progreso &
+			# si no se puede genera la tinyurl prueba varias veces
+			u=`proxychains wget -U Mozilla "https://tinyurl.com/create.php?url=data:text/html;charset=utf-8;base64,$m" -qO - \
+			| grep "'https://tinyurl.com/" | head -n 1 | cut -d "'" -f 2`
+			echo "$u" && break || echo "no se genero la tinyURL" | error
+		done
 		echo "$u" | papelera
-		echo "$u" | mostrar
-		# no se por que no genera la tinyurl a veces
+		url "$u"
 		;;
-	3 )
-		# publicar en Uploader con Tor
-		# genera el mensaje y lo muestra en base64
-		m=`echo "$ef" | mcrypt -z -u -k "$k" -F | base64 -w0`
+	4 )
+		exit
 		# http://uploadpie.com/
-		u=`wget -U Mozilla "https://tinyurl.com/create.php?url=data:text/html;charset=utf-8;base64,$m" -qO - \
-		| grep "https://tinyurl.com/"` | progreso
-		echo "$u" > /dev/stderr
-		echo "$u" | papelera
-		echo "$u" | mostrar
-		# no se por que no genera la tinyurl a veces
-		;;
 	esac
 	;;
 	1 )
 	# Descifrar
 
 	# mensaje archivo o URL
-	MENU=`echo -e "Mensaje Archivo Dirección_de_internet" | opciones -t "Descifrar" -m "¿Donde queres buscar?"` || exit
+	MENU=`echo -e "Mensaje Archivo En_la_red" | opciones -t "Descifrar" -m "¿Donde queres buscar?"` || exit
 	case $MENU in
 		0 )
 			# descifrado
 			t=`mensaje` || exit
 			k=`clave`
-			m=`$t | sed 's/\ [^1-9A-Za-z]=//g'| base64 -d | mdecrypt - -z -k "$k" -F` || error && exit
+			m=`$t | sed 's/\ [^1-9A-Za-z]=//g'| base64 -d | mdecrypt - -k "$k" -F` || error && exit
 
 			# lo guarda en la papelera y lo muestra
 			echo "$m" | papelera
@@ -149,12 +157,27 @@ case $MENU in
 			URL=`url` || exit
 			# mensaje descifrado en archivo
 			p=`clave`
-			sf=`mktemp`
-			# visitar la pagina de internet con Tor
-			proxychains wget "$URL" -O $sf | progreso
-			m=`steghide extract -p "$p" -sf $sf -xf -`
+
+			# descargas
+			if [ "$(echo $URL | grep tinyurl)" ]; then
+				# contenida en la URL
+				sf=`proxychains wget -S "$URL" -qO /dev/null 2> /dev/stdout | grep "Location:" | cut -d, -f2`
+			else
+				# contenida en el archivo
+				sf=`proxychains wget "$URL" -qO -`
+				tipo=`echo "$f" | file -i - | sed 's/^.*:\ //g; s/\/.*$//g'`
+			fi
+			# interpreta depende si es cifrado o estenografia
+			if [ "$tipo" == "text" ]; then
+				# si es un texto
+				m=`echo $sf \
+				| sed -e :a -e 's/<[^>]*>//g;/</N;//ba' \
+				| sed 's/\ [^1-9A-Za-z]=//g'| base64 -d | mdecrypt - -k "$p" -F`
+			else
+				# si es archivo
+				m=`echo "$sf" | steghide extract -p "$p" -sf - -xf -`
+			fi
 			# borrar el archivo temporal para siempre
-			shred -uz -n 10	$sf
 			echo "$m" | mostrar
 		;;
 	esac
